# 1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array
Use the list given below: (or create your own list)

list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]


In [14]:
import numpy as np
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
one_d=np.array(list_temperature)
print(f'{one_d},{one_d.ndim}D')

[3.04 1.65 5.76 1.66 1.54 4.69 2.68],1D


# 2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68
Use the weights given below: (or create your own list)

weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]


In [381]:
import numpy as np
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
one_d_w=np.array(weights)
res=one_d_w[np.where(one_d_w>68)] # or one_d_w[one_d_w>68]
print(res)

[74.2 85.  74.  70.5 86.  82. ]


# 3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? 
If yes, describe the function)


In [384]:
import numpy as np
ran=np.random.randint(20,40,(10,))
print(ran)

[26 39 34 30 27 26 38 30 30 23]


In [386]:
#---Yes it posiible to generate same random numbers for a given number of times by using seed() function of random module.
np.random.seed(42)
ran=np.random.randint(20,40,(10,))
print(ran)

[26 39 34 30 27 26 38 30 30 23]


# 4. Write a program to get the fifth power of the first five positive integers


In [389]:
import numpy as np
array=np.array([1,2,3,4,5])
print(array)
print(array**5)

[1 2 3 4 5]
[   1   32  243 1024 3125]


# 5. Write a program to create an array of all the odd integers from 50 to 100


In [392]:
import numpy as np
arr=np.arange(50,101,1)
odd=arr[arr%2!=0]
print(odd)

[51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


# 6. Write a program to calculate the sum of each column
Use the array given below: (or create your own array)

A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]


In [395]:
import numpy as np
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
arr=np.array(A)
print(arr)
s=np.sum(A,axis=0)
print(s)

[[ 1  4  8]
 [ 5  7  3]
 [ 9 14  2]]
[15 25 13]


# 7. Write a code to get the element-wise remainder of an array after division by 8
Use the list given below:

num = [42, 87, 90, 14, 32, 75, 61, 80, 92]


In [398]:
import numpy as np
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
a=np.array(num)
res=a%8
print("Remainder-",res)

Remainder- [2 7 2 6 0 3 5 0 4]


# 8. Create a 2D numpy array from a 1D array of 20 elements of your choice. 
## Further, subset the first 5 elements from the second element of a resulting 2D array


In [401]:
import numpy as np
np.random.seed(42)
one=np.arange(1,21)
print(one,'\n')
two=np.reshape(one,(4,5))
print(two,'\n')
print(two[1,])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[ 6  7  8  9 10]


# 9. Write a program to find common values between two arrays.
Use the lists given below:

prices_monday = [10, 30, 50, 60, 90]

prices_tuesday = [50, 20, 80, 125, 10, 70]


In [404]:
import numpy as np
prices_monday = [10, 30, 50, 60, 90]
prices_tuesday = [50, 20, 80, 125, 10, 70]
a1=np.array(prices_monday)
a2=np.array(prices_tuesday)
comm=np.intersect1d(a1,a2)
print(comm)

[10 50]


# 10. Write a program to find BMI of the patients whose height and weight is provided in the list given below
Use the lists given below:

list of weights (in kg)
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [409]:
import numpy as np
weights = [57, 69, 54, 65, 71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]
w=np.array(weights)
h=np.array(heights)
bmi=w/(h**2)
print("BMI of patients:",bmi)

BMI of patients: [22.54657648 22.53061224 19.59645812 21.46915048 26.39797739 20.9572742
 23.922423  ]


# 11. Write a program to add a new column ([5,7]) at the last position in the array given below
Use the array given below:

array1 = [[[3, 4], [8, 2],[5, 9]]]


In [412]:
import numpy as np
array1 = np.array([[[3, 4], 
                    [8, 2],
                    [5, 9]]])

p=np.append(array1,np.array([[[5],[7],[0]]]),axis=2)
print(p)


[[[3 4 5]
  [8 2 7]
  [5 9 0]]]


# 12. Write a code to print the identity matrix of order 5


In [415]:
import numpy as np
i=np.identity(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 13. Write a program to transpose a matrix
Use the matrix given below:

M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]


In [418]:
import numpy as np
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
transpose=np.transpose(M)
print(transpose)

[[15  7 54  0]
 [17 42  3 87]
 [45 15 61 16]
 [56 63 41 20]]


# 14. Write a program to combine the two arrays vertically
Use the arrays given below: (or create your own array)

A1 = [[5, 9], [7, 6]]

A2 = [[8,-7], [0,4]]


In [421]:
import numpy as np
A1 = [[5, 9], [7, 6]]
A2 = [[8,-7], [0,4]]

v_s=np.vstack((A1,A2))
print(v_s)

[[ 5  9]
 [ 7  6]
 [ 8 -7]
 [ 0  4]]


# 15. Write a code to combine the two arrays horizontally
Use the arrays given below: (or create your own array)

A1 = [[-81, 75, 40], [27, 67, 52]]

A2 = [[15, 54], [39, 56]]


In [424]:
import numpy as np
A1 = [[-81, 75, 40], [27, 67, 52]]
A2 = [[15, 54], [39, 56]]
h_s=np.hstack((A1,A2))
print(h_s)

[[-81  75  40  15  54]
 [ 27  67  52  39  56]]


# 16. Write a code to divide the array into three sub-arrays containing equal number of rows
Use the array given below:

A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]



In [427]:
import numpy as np
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]
a=np.array(A)
s=np.split(a,3)
s

[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

# 17. Write a program to divide the array into two sub-arrays containing equal number of columns
Use the array given below:

B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]


In [430]:
import numpy as np
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
ar=np.array(B)
split=np.split(ar,2,axis=1)
print(split)

[array([[ 8,  7],
       [ 2, -3],
       [ 8,  5]]), array([[ 0,  9],
       [ 5, 10],
       [-1,  3]])]


# 18. Write a program to perform one-to-one mapping of the two lists
Use the lists given below: (or create your own lists)

L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]


In [433]:
import numpy as np
L1 = [45, 67, 56, 71, 54, 62, 56]
L2 = [21, 52, 64, 10, 49, 74, 26]
s=np.array(list(zip(L1,L2)))
print(s)

[[45 21]
 [67 52]
 [56 64]
 [71 10]
 [54 49]
 [62 74]
 [56 26]]


# 19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array
Use the list given below:

numbers = [6, 5, 3, 15]


In [436]:
import numpy as np
numbers=[6,5,3,15]
arr=np.array(numbers)
for i in np.nditer(arr):
    res=(2*i - 1) / (i + 5)
    print(res)

1.0
0.9
0.625
1.45
