# 1. Explain Data Analysis in Your Own Words.


- Data Analysis means looking at data carefully to understand it and finding the 

  patterns and relationships in the data.

# 2. Generate Arrays of Different Dimensions.

Generate five NumPy arrays using np.arange():

0D array (a single value)

1D array (e.g., 0 to 4)

2D array (reshape a 1D array into 2x3)
 
4D array (bonus!)




In [119]:
import numpy as np
a0=np.array(1)
a1=np.arange(0,4)
a2=np.arange(6).reshape(2,3)
a3=np.arange(8).reshape(2,2,2)
a4=np.arange(16).reshape(2,2,2,2)
print(a0,a0.ndim,"D")
print()
print(a1,a1.ndim,"D")
print()
print(a2,a2.ndim,"D")
print()
print(a3,a3.ndim,"D")
print()
print(a4,a4.ndim,"D")

1 0 D

[0 1 2 3] 1 D

[[0 1 2]
 [3 4 5]] 2 D

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 3 D

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]] 4 D


# 3. Print the datatype, shape, size, and dimension of each of the above arrays

Use .dtype, .shape, .size, and .ndim.


In [125]:
print(f"{a0} dtype-{a0.dtype} , shape-{a0.shape} , size-{a0.size} , Dimension-{a0.ndim}")
print()
print(f"{a1} dtype-{a1.dtype} , shape-{a1.shape} , size-{a1.size} , Dimension-{a1.ndim}")
print()
print(f"{a2} dtype-{a2.dtype} , shape-{a2.shape} , size-{a2.size} , Dimension-{a2.ndim}")
print()
print(f"{a3} dtype-{a3.dtype} , shape-{a3.shape} , size-{a3.size} , Dimension-{a3.ndim}")
print()
print(f"{a4} dtype-{a4.dtype} , shape-{a4.shape} , size-{a4.size} , Dimension-{a4.ndim}")

1 dtype-int32 , shape-() , size-1 , Dimension-0

[0 1 2 3] dtype-int32 , shape-(4,) , size-4 , Dimension-1

[[0 1 2]
 [3 4 5]] dtype-int32 , shape-(2, 3) , size-6 , Dimension-2

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] dtype-int32 , shape-(2, 2, 2) , size-8 , Dimension-3

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]] dtype-int32 , shape-(2, 2, 2, 2) , size-16 , Dimension-4


# 4. Generate a NumPy Array Using Random Function.

Use np.random.rand() to generate a 1D array of 5 random values.


In [128]:
import numpy as np
ar=np.random.rand(5)
print(ar)

[0.02271102 0.24981537 0.263523   0.7625376  0.0962589 ]


# 5. Access & Slice Elements

Using the array you created in Question 4 (a 1D array of 5 random values generated with np.random.rand()):

Print the element at the second index.

Print the first three elements.


In [131]:
print(f"Element at index 2 is {ar[2]}")
print(f"First 3 elements are {ar[0:3]}")

Element at index 2 is 0.2635230011639491
First 3 elements are [0.02271102 0.24981537 0.263523  ]


# 6. Create a 2D Array with Random Numbers.

Use np.random.randint() to generate a 2D array of shape 3x3 with values from 1 to 100.


In [134]:
import numpy as np
a2d=np.random.randint(1,101,(3,3))
print(a2d)

[[64 30 58]
 [39 98 29]
 [24 22 45]]


# 7. Create Evenly Spaced Values.

Create an array of 5 evenly spaced values between 0 and 1 using np.linspace()

In [137]:
import numpy as np
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


# 8. Create a 3x3 Matrix:

Filled with ones

With ones only on the diagonal

Filled with zeros


In [140]:
ar1=np.ones((3,3))
ar2=np.identity(3)
ar3=np.zeros((3,3))
print(ar1,'\n')
print(ar2,'\n')
print(ar3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
