# 1. Create two 1D arrays

One containing multiples of 3 in variable (a)

One containing multiples of 5 in variable (b)


In [3]:
import numpy as np
a=np.arange(3,30,3)
b=np.arange(5,50,5)
print(a)
print(b)

[ 3  6  9 12 15 18 21 24 27]
[ 5 10 15 20 25 30 35 40 45]


# 2. Perform Arithmetic Operations

Using the arrays a and b from the previous task, perform element-wise addition, subtraction, multiplication, and division.


In [8]:
print(np.add(a,b))
print(np.subtract(b,a))
print(np.multiply(a,b))
print(np.divide(b,a))

[ 8 16 24 32 40 48 56 64 72]
[ 2  4  6  8 10 12 14 16 18]
[  15   60  135  240  375  540  735  960 1215]
[1.66666667 1.66666667 1.66666667 1.66666667 1.66666667 1.66666667
 1.66666667 1.66666667 1.66666667]


# 3. Statistical Summary
For the arrays a and b (created in previous questions or create a new one):

Find and print the Mean (average)

Find and print the Median

Find and print the Mode

Find and print the Range (Max - Min)

Find and print the Standard Deviation

Find and print the Variance

Find and print the Sum



In [43]:
arr=np.arange(1,21)
print(arr)
print("Mean",np.mean(arr))
print("Median",np.median(arr))
print("Range",np.max(arr)-np.min(arr))
print("Std",np.std(arr))
print("Variance",np.var(arr))
print("Sum",np.sum(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Mean 10.5
Median 10.5
Range 19
Std 5.766281297335398
Variance 33.25
Sum 210


# 4. Use flip() to Reverse

Create a 1D NumPy array with values from 10 to 50 using np.arange(). Reverse the array using np.flip().


In [135]:
ar=np.arange(10,51)
print(ar)
rev=np.flip(ar)
print(rev)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# 5. Reverse Without flip()
Achieve the same reversed array without using np.flip().


In [138]:
ar=np.arange(10,51)
print(ar)
r=ar[::-1]
print(r)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# 6. Boolean Indexing
Using the reversed array (from the previous task or a newly created one), do the following:

Create a boolean array where each value checks whether the element is greater than 30.

Print the boolean array (it will contain only True or False values).

Use this boolean array to filter out only the elements that are greater than 30 from the original array.


In [141]:
print(r)
b_arr=r>30
print(b_arr)
print('filter-',r[b_arr])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False False
 False False False False False False False False False False False False
 False False False False False]
filter- [50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31]


# 7. Conditional Replacement
Replace all even numbers in the reversed array (or a newly created array) with -1 and print the modified array.


In [144]:
ar=np.arange(10,51)
r=ar[::-1]
print(r)
r[r%2==0]=-1
print(r)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[-1 49 -1 47 -1 45 -1 43 -1 41 -1 39 -1 37 -1 35 -1 33 -1 31 -1 29 -1 27
 -1 25 -1 23 -1 21 -1 19 -1 17 -1 15 -1 13 -1 11 -1]


# 8. Random 2D Array Transformation

Generate a 2D array of shape (3, 3) with random integers between 10 and 99. Transpose the array and then flatten it into a 1D array.



In [196]:
array=np.random.randint(10,100,(3,3))
print(array)
t=np.transpose(array)
f=t.flatten()
print("Transpose array-")
print(t)
print("flatten array-")
print(f)

[[52 39 19]
 [54 98 98]
 [97 80 31]]
Transpose array-
[[52 54 97]
 [39 98 80]
 [19 98 31]]
flatten array-
[52 54 97 39 98 80 19 98 31]


# 9. Modify Array Elements

Take the flattened array from Question 8.

Insert the value 99 at index 2.

Append the value 100 at the end.

Delete the element at index 3.


In [276]:
import numpy as np
f=np.array([45,67,54,78,19,39,23,82,91])
print(f)
f=np.insert(f,2,99)
print("insert",f)
f=np.append(f,100)
print("append",f)       
f=np.delete(f,3)       
print("delete",f)


[45 67 54 78 19 39 23 82 91]
insert [45 67 99 54 78 19 39 23 82 91]
append [ 45  67  99  54  78  19  39  23  82  91 100]
delete [ 45  67  99  78  19  39  23  82  91 100]


# 10. Array Iteration

Create a 2D NumPy array of shape (2, 3) with any integers.

Iterate through the array using a basic for loop.

Then, iterate using np.nditer().


In [279]:
import numpy as np
a=np.random.randint(1,11,(2,3))
print(a,a.ndim,"D")

[[5 9 1]
 [7 1 6]] 2 D


In [285]:
for i in a:
    for j in i:
        print(j)

5
9
1
7
1
6


In [287]:
for i in np.nditer(a):
    print(i)

5
9
1
7
1
6


# 11. Operations on Random Float Arrays
Generate two 1D arrays (length 5 each) with random float numbers between 1 and 10.

Perform element-wise operations: +, -, *, /, %, //.

Apply mathematical functions: np.sqrt(), np.exp(), np.sin(), np.log().


In [290]:
import numpy as np

a=np.random.uniform(1,10,5)
b=np.random.uniform(1,10,5)
print("a:",a)
print("b:",b)

print("\nAddition",a+b)
print("\nSubtraction",a-b)
print("\nMultiplication",a*b)
print("\nDivision",a/b)
print("\nModulus",a%b)
print("\nFloor Division",a//b)
print("\nSquare Root of a",np.sqrt(a))
print("\nExponential of a",np.exp(a))
print("\nSine of a",np.sin(a))
print("\nLog of a",np.log(a))

a: [8.02416243 4.64503167 3.72419491 9.31847664 6.82830177]
b: [4.44823162 1.52570126 9.55778781 6.472861   9.55260137]

Addition [12.47239404  6.17073293 13.28198272 15.79133765 16.38090313]

Subtraction [ 3.57593081  3.11933041 -5.8335929   2.84561564 -2.7242996 ]

Multiplication [35.69333301  7.08693069 35.59506471 60.31720407 65.2280448 ]

Division [1.80389942 3.0445224  0.3896503  1.43962255 0.71481071]

Modulus [3.57593081 0.06792788 3.72419491 2.84561564 6.82830177]

Floor Division [1. 3. 0. 1. 0.]

Square Root of a [2.83269526 2.15523355 1.92981733 3.052618   2.61310194]

Exponential of a [ 3053.86239545   104.06666149    41.43785804 11141.99568768
   923.62095845]

Sine of a [ 0.98555416 -0.99773235 -0.55019877  0.10610123  0.51851768]

Log of a [2.08245729 1.53579819 1.3148507  2.23199917 1.921076  ]
