# 1. Understand Broadcasting in Your Own Words


##### Broadcasting is a concept that allows operations between arrays of different shapes or sizes without needing to manually reshape.

# 2. Apply Broadcasting with Scalar
Create a 3x3 array filled with numbers from 1 to 9. Add 10 to the entire array using broadcasting and Print the updated array.


In [74]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
u_arr=arr+10
print(u_arr)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


# 3. Broadcasting with Two Arrays
Create a 3x1 array (column vector) and a 1x3 array (row vector), then perform an addition operation between them.
	Example: a = np.array([[1], [2], [3]])
    b = np.array([[10, 20, 30]])


In [79]:
import numpy as np
a=np.array([[1],[2],[3]])
b=np.array([[10,20,30]])
result=a+b
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


# 4. Use np.where() for Conditional Selection
Create a 1D array of values from 1 to 10. Use np.where() to replace:

All even numbers with 0

All odd numbers with 1


In [82]:
import numpy as np
arr=np.arange(1,11)
print(arr)
res=np.where(arr%2==0,0,1)
print(res)

[ 1  2  3  4  5  6  7  8  9 10]
[1 0 1 0 1 0 1 0 1 0]


# 5. Create a Mask Using Multiple Conditions

Create an array of values from 10 to 30. Use boolean masking to filter elements:

Greater than 15 AND divisible by 3


In [85]:
import numpy as np
ar=np.arange(10,31)
print(ar)
m=(ar>15)&(ar%3==0)
r=ar[m]
print(r)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[18 21 24 27 30]


# 6. Use np.where() with Two Arrays
Create two arrays of 5 elements each.

Use np.where() to pick elements from array A where values in array B are greater than 5, otherwise pick from B.


In [88]:
import numpy as np
a=np.array([2,7,4,9,1])
b=np.array([5,3,8,2,6])
res=np.where(a>5,a,b)
print(res)

[5 7 8 9 6]


# 7. Create a Custom Grading System
Generate an array of 10 random marks between 0 and 100. Use np.where() to assign grades:

'A' for marks >= 75

'B' for 50–74

'C' for below 50


In [91]:
import numpy as np
marks=np.random.randint(0,101,10)
print("marks:",marks)
g=np.where(marks>=75,'A',np.where(marks>=50,'B','C'))
print("grades:",g)

marks: [34 95 19 78 54 92 69 17 10 46]
grades: ['C' 'A' 'C' 'A' 'B' 'A' 'B' 'C' 'C' 'C']


# 8. Compare Two Arrays Element-wise

Create two arrays of shape (3, 3). Print a boolean array that shows where the elements are equal.


In [94]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,21,3],[4,5,61],[1,8,9]])
c=np.where(a==b,True,False)
print(c)

[[ True False  True]
 [ True  True False]
 [False  True  True]]


# 9. Use np.any() and np.all()

On a random 3x3 integer array:

Check if any value is greater than 90.

Check if all values are positive.

Delete the element at index 3.


In [97]:
import numpy as np
a=np.random.randint(10,101,9).reshape(3,3)
print(a)
p1=np.any(a>90)
print(p1)
p2=np.all(a>0)
print(p2)
p3=np.delete(a,3)
print(p3)

[[99 30 92]
 [66 30 46]
 [53 22 51]]
True
True
[99 30 92 30 46 53 22 51]
