In [1]:
import numpy as np

ARRAY CREATION

In [9]:
arr1=np.array([1,2,4,5,6])
print(arr1)

[1 2 4 5 6]


In [21]:
arr2=np.zeros((6))
print(arr2)

[0. 0. 0. 0. 0. 0.]


In [29]:
arr3=np.zeros((6,2))
print(arr3)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [31]:
arr3=np.ones((6))
print(arr3)

[1. 1. 1. 1. 1. 1.]


In [33]:
arr3=np.ones((6,2))
print(arr3)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [41]:
arr4=np.full((4,3),6)
arr4

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [45]:
arr4=np.full((4),7)
arr4

array([7, 7, 7, 7])

In [49]:
arr5=np.arange(2,9,3) #start,stop,step
arr5

array([2, 5, 8])

In [63]:
arr6=np.linspace(1,10,5) #incluse start and stop values
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [71]:
arr7=np.eye(3)
arr7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
arr8=np.random.rand(3) #between 0 and 1
arr8

array([0.37882117, 0.95344366, 0.11382698])

In [90]:
arr8=np.random.randn(5)
arr8

array([-0.0204979 , -1.83511589, -0.20443044,  0.9083654 ,  1.94584094])

In [120]:
arr8=np.random.randint(3,8,7)
uni=set(arr8)
print(arr8)
print(uni)

[3 5 5 5 7 7 5]
{3, 5, 7}


ARRAY PROPERTIES AND ATTRIBUTES

In [152]:
arr9=np.array([[1,2,3],
              [4,5,6]])
print(arr9)

print(arr9.shape) # no. rows and columns
print(arr9.size) #total no. of elements
print(arr9.ndim) # 1D OR 2D OR 3D
print(arr9.dtype) #data type

str_arr=arr9.astype(str)
print(str_arr) #convt to string type

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int32
[['1' '2' '3']
 ['4' '5' '6']]


ARRAY MATHS OPERATIONS

In [179]:
arr10=np.array([10,50,40])
print(np.add(arr10,5))
print(np.subtract(arr10,5))
print(np.multiply(arr10,5))
print(np.divide(arr10,5))
print(np.floor_divide(arr10,4))
print(np.power(arr10,5))
print(np.mod(arr10,6))

[15 55 45]
[ 5 45 35]
[ 50 250 200]
[ 2. 10.  8.]
[ 2 12 10]
[   100000 312500000 102400000]
[4 2 4]


ARRAY STATISTICAL OR AGGREGATE FUNCTIONS

In [252]:
arr11=np.array([[1,2,3],
               [4,5,6]])
print(arr11)
print(np.sum(arr11,axis=1))
print(np.mean(arr11,axis=0))
print(np.min(arr11))
print(np.max(arr11))
print(np.var(arr11))
print(np.std(arr11))
print(arr11.argmin())
print(arr11.argmax())

[[1 2 3]
 [4 5 6]]
[ 6 15]
[2.5 3.5 4.5]
1
6
2.9166666666666665
1.707825127659933
0
5


ARRAY INDEXING AND SLICING

In [229]:
arr12=np.array([10,20,30,40,50,60,70,80,90])
print(arr12)
print(arr12[0])
print(arr12[4])

print(arr12[2:8:3])
print(arr12[::-1])

[10 20 30 40 50 60 70 80 90]
10
50
[30 60]
[90 80 70 60 50 40 30 20 10]


In [231]:
#fancy indexing-selecting multi elements at once
print(arr12[[0, 4, 8]])

[10 50 90]


In [245]:
# boolean masking or filtering -filtering values based on some condition
print(arr12[arr12>25])

[30 40 50 60 70 80 90]


ARRAY RESHAPING AND MANIPULATION

In [248]:
arr13=np.array([10,20,30,40,50,60])
res_array=arr13.reshape(2,3)
print(res_array)

[[10 20 30]
 [40 50 60]]


In [260]:
print(arr11.ravel()) #view - original array modified
print(arr11.flatten()) #copy - original array uneffected


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [262]:
arr14=np.array([10,20,30,40,50,60,70,80])
new_arr=np.insert(arr14,3,100)
print(new_arr)

[ 10  20  30 100  40  50  60  70  80]


In [276]:
arr14=np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
new_arr=np.insert(arr14,2,[100,90,0],axis=1)
print(new_arr)

[[ 10  20 100  30]
 [ 40  50  90  60]
 [ 70  80   0  90]]


In [282]:
new_a=np.append(arr14,[3,5])
print(new_a)

[10 20 30 40 50 60 70 80 90  3  5]


In [290]:
a1=np.array([1,2,3])
a2=np.array([5,6,7])
na=np.concatenate((a1,a2))
print(na)

[1 2 3 5 6 7]


In [300]:
print(np.delete(a1,2))
print(np.delete(arr14,0,axis=1))
print(np.delete(arr14,0,axis=0))

[1 2]
[[20 30]
 [50 60]
 [80 90]]
[[40 50 60]
 [70 80 90]]


In [308]:
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

[[1 2 3]
 [5 6 7]]
[1 2 3 5 6 7]


In [328]:
print(np.split(arr14,3))

[array([[10, 20, 30]]), array([[40, 50, 60]]), array([[70, 80, 90]])]


HANDLING MISSING VALUES

In [335]:
array=np.array([1,2,np.nan,4])
print(array)
print(np.isnan(array))
print(np.nan_to_num(array,nan=90))

[ 1.  2. nan  4.]
[False False  True False]
[ 1.  2. 90.  4.]
